import { Escalation } from './types';

// Priority calculation logic (same as escalationEngine)
function calculatePriorityForMock(score: number, issueType: string): 'P1' | 'P2' | 'P3' {
  if (issueType === 'urgent') {
    if (score >= 60) return 'P1';
    if (score >= 40) return 'P2';
    return 'P3';
  }

  if (issueType === 'delayed' || issueType === 'follow-up') {
    if (score >= 70) return 'P1';
    if (score >= 45) return 'P2';
    return 'P3';
  }

  if (issueType === 'complaint') {
    if (score >= 65) return 'P1';
    if (score >= 40) return 'P2';
    return 'P3';
  }

  if (score > 75) return 'P1';
  if (score >= 50) return 'P2';
  return 'P3';
}

const mockEscalationsData = [
  {
    id: 'MOCK-001',
    subject: 'Payment processing failed - Urgent',
    body: 'Customer unable to complete payment. Order stuck in pending state for 2 hours. System shows gateway timeout errors. This is affecting revenue.',
    sent_at: '2026-03-20T08:15:00Z',
    sender: 'customer-support@example.com',
    sender_name: 'John Smith',
    escalation_score: 95,
    sentiment_score: -0.85,
    keyword_score: 90,
    delay_signal: 3,
    priority: 'P1',
    issue_type: 'urgent',
    summary: 'Payment gateway down, affecting customer transactions',
    action_required: 'Immediate engineering escalation to payment team',
    status: 'open',
    owner: 'eng-team',
    tat_hours: 1,
    created_at: '2026-03-20T08:15:00Z',
  },
  {
    id: 'MOCK-002',
    subject: 'Database connection pool exhausted',
    body: 'Production database showing connection pool exhaustion. Response times degrading rapidly. Need immediate mitigation. All transactions affected.',
    sent_at: '2026-03-20T07:45:00Z',
    sender: 'ops@example.com',
    sender_name: 'Sarah Johnson',
    escalation_score: 92,
    sentiment_score: -0.80,
    keyword_score: 88,
    delay_signal: 4,
    priority: 'P1',
    issue_type: 'urgent',
    summary: 'Database connectivity issue impacting all services',
    action_required: 'DBA escalation required immediately',
    status: 'in-progress',
    owner: 'dba-team',
    tat_hours: 0.5,
    created_at: '2026-03-20T07:45:00Z',
  },
  {
    id: 'MOCK-003',
    subject: 'Customer complaint - Late delivery package',
    body: 'Order #12345 promised delivery date missed by 5 days. Customer very upset. Requesting refund and compensation.',
    sent_at: '2026-03-19T14:20:00Z',
    sender: 'support@example.com',
    sender_name: 'Mike Chen',
    escalation_score: 68,
    sentiment_score: -0.72,
    keyword_score: 65,
    delay_signal: 2,
    priority: 'P2',
    issue_type: 'complaint',
    summary: 'Late delivery causing customer dissatisfaction',
    action_required: 'Shipping team follow-up and compensation review',
    status: 'in-progress',
    owner: 'customer-success',
    tat_hours: 4,
    created_at: '2026-03-19T14:20:00Z',
  },
  {
    id: 'MOCK-004',
    subject: 'API endpoint timing out intermittently',
    body: 'Users reporting 504 gateway timeouts on the /api/products endpoint. Issue intermittent, happens ~20% of requests. Load seems normal.',
    sent_at: '2026-03-19T11:30:00Z',
    sender: 'dev-team@example.com',
    sender_name: 'Alex Rodriguez',
    escalation_score: 72,
    sentiment_score: -0.65,
    keyword_score: 70,
    delay_signal: 2,
    priority: 'P2',
    issue_type: 'delayed',
    summary: 'Intermittent API timeouts affecting user experience',
    action_required: 'Investigation needed for performance bottleneck',
    status: 'in-progress',
    owner: 'backend-team',
    tat_hours: 2,
    created_at: '2026-03-19T11:30:00Z',
  },
  {
    id: 'MOCK-005',
    subject: 'Follow-up: Mobile app crash on iOS',
    body: 'Continuing discussion about iOS app crashes reported in previous ticket. New crash logs show memory leak in image caching module. Analysis in progress.',
    sent_at: '2026-03-18T16:45:00Z',
    sender: 'mobile-team@example.com',
    sender_name: 'Emma Wilson',
    escalation_score: 55,
    sentiment_score: -0.45,
    keyword_score: 50,
    delay_signal: 1,
    priority: 'P2',
    issue_type: 'follow-up',
    summary: 'iOS app memory leak investigation update',
    action_required: 'Continue memory profiling and update stakeholders',
    status: 'in-progress',
    owner: 'mobile-team',
    tat_hours: 6,
    created_at: '2026-03-18T16:45:00Z',
  },
  {
    id: 'MOCK-006',
    subject: 'Data inconsistency between regions',
    body: 'US East region showing different product prices than EU West region. Affecting A/B test results. Looks like cache sync issue.',
    sent_at: '2026-03-18T09:15:00Z',
    sender: 'analytics@example.com',
    sender_name: 'Lisa Park',
    escalation_score: 65,
    sentiment_score: -0.58,
    keyword_score: 62,
    delay_signal: 2,
    priority: 'P2',
    issue_type: 'delayed',
    summary: 'Regional data synchronization issue',
    action_required: 'Investigate cache layer sync mechanisms',
    status: 'in-progress',
    owner: 'data-eng',
    tat_hours: 3,
    created_at: '2026-03-18T09:15:00Z',
  },
  {
    id: 'MOCK-007',
    subject: 'Resolved: Rate limiting too aggressive',
    body: 'Previously reported aggressive rate limiting has been adjusted. Legitimate traffic no longer being blocked. Issue resolved.',
    sent_at: '2026-03-17T13:20:00Z',
    sender: 'platform-team@example.com',
    sender_name: 'David Kumar',
    escalation_score: 38,
    sentiment_score: 0.20,
    keyword_score: 35,
    delay_signal: 0,
    priority: 'P3',
    issue_type: 'other',
    summary: 'Rate limiting configuration adjusted successfully',
    action_required: 'Monitor for regression',
    status: 'resolved',
    owner: 'platform-team',
    tat_hours: 8,
    created_at: '2026-03-17T08:00:00Z',
    resolved_at: '2026-03-17T13:20:00Z',
  },
  {
    id: 'MOCK-008',
    subject: 'Customer feedback: UI confusing',
    body: 'User reports confusion with the new dashboard layout. Navigation not intuitive. Suggesting improvement to onboarding.',
    sent_at: '2026-03-17T10:50:00Z',
    sender: 'ux@example.com',
    sender_name: 'Rachel Thompson',
    escalation_score: 42,
    sentiment_score: -0.35,
    keyword_score: 40,
    delay_signal: 1,
    priority: 'P3',
    issue_type: 'complaint',
    summary: 'UX improvement request for dashboard',
    action_required: 'Design review and user testing',
    status: 'open',
    owner: 'ux-team',
    tat_hours: 12,
    created_at: '2026-03-17T10:50:00Z',
  },
  {
    id: 'MOCK-009',
    subject: 'Billing discrepancy - Customer overpaid',
    body: 'Customer charged twice for same transaction. Requesting refund of $299.99. Invoice #INV-2025-8845.',
    sent_at: '2026-03-19T15:30:00Z',
    sender: 'billing@example.com',
    sender_name: 'Tom Anderson',
    escalation_score: 70,
    sentiment_score: -0.68,
    keyword_score: 68,
    delay_signal: 2,
    priority: 'P2',
    issue_type: 'urgent',
    summary: 'Duplicate charge requiring immediate refund',
    action_required: 'Finance team to process refund within 24 hours',
    status: 'open',
    owner: 'finance',
    tat_hours: 1,
    created_at: '2026-03-19T15:30:00Z',
  },
  {
    id: 'MOCK-010',
    subject: 'Security audit findings - Minor issues',
    body: 'Annual security audit completed. Found 2 low-severity issues and 1 medium. Detailed report attached. No critical findings.',
    sent_at: '2026-03-16T11:00:00Z',
    sender: 'security@example.com',
    sender_name: 'Officer Sam',
    escalation_score: 48,
    sentiment_score: -0.25,
    keyword_score: 45,
    delay_signal: 1,
    priority: 'P3',
    issue_type: 'other',
    summary: 'Annual security audit with minor findings',
    action_required: 'Schedule remediation planning session',
    status: 'open',
    owner: 'security-team',
    tat_hours: 24,
    created_at: '2026-03-16T11:00:00Z',
  },
  {
    id: 'MOCK-011',
    subject: 'Email delivery failures - Transactional',
    body: 'Order confirmation emails not reaching customers. Bounce rate at 15%. Affects customer experience. Need immediate fix.',
    sent_at: '2026-03-20T06:30:00Z',
    sender: 'platform@example.com',
    sender_name: 'Nina Patel',
    escalation_score: 78,
    sentiment_score: -0.70,
    keyword_score: 75,
    delay_signal: 3,
    priority: 'P1',
    issue_type: 'urgent',
    summary: 'Critical email delivery issue for transactional emails',
    action_required: 'Contact email provider and check DNS/SMTP settings',
    status: 'in-progress',
    owner: 'platform-team',
    tat_hours: 1,
    created_at: '2026-03-20T06:30:00Z',
  },
  {
    id: 'MOCK-012',
    subject: 'Follow-up on previous enhancement request',
    body: 'Checking status on the dark mode feature request from last week. When can we expect this feature?',
    sent_at: '2026-03-15T14:15:00Z',
    sender: 'product@example.com',
    sender_name: 'Casey Lee',
    escalation_score: 35,
    sentiment_score: -0.20,
    keyword_score: 30,
    delay_signal: 0,
    priority: 'P3',
    issue_type: 'follow-up',
    summary: 'Status check on dark mode feature',
    action_required: 'Provide timeline update to requester',
    status: 'resolved',
    owner: 'product-team',
    tat_hours: 48,
    created_at: '2026-03-15T09:00:00Z',
    resolved_at: '2026-03-15T14:15:00Z',
  },
];

// Recalculate priorities based on improved logic
export const mockEscalations: Escalation[] = mockEscalationsData.map((esc) => {
  return {
    ...esc,
    priority: calculatePriorityForMock(esc.escalation_score, esc.issue_type),
  } as Escalation;
});
